name: Main workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node-version:
          - 13.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore esy cache
        uses: actions/cache@v1
        id: esy
        with:
          path: ~/.esy
          key: ${{ runner.os }}-esy-${{ hashFiles('esy.lock/index.json') }}
          restore-keys: |
            ${{ runner.os }}-esy-

      - name: Install esy
        run: npm install --global esy

      - name: Install and build opam packages
        run: esy

      - name: Copy and rename binary
        run: cp _build/default/src/tree.exe ./tree

      - name: Upload binary to artifact
        uses: actions/upload-artifact@v1
        with:
          name: re-tree-${{ matrix.os }}
          path: tree
